---
cro: 1
name: ingredient.guru
entrypoint: service.p6
id: ingredient.guru
endpoints: 
  - 
    name: HTTP
    port-env: INGREDIENT_GURU_PORT
    id: http
    host-env: INGREDIENT_GURU_HOST
    protocol: http
links:  []
env:  []
...