---
links:  []
cro: 1
endpoints: 
  - 
    port-env: INGREDIENT_GURU_PORT
    protocol: http
    name: HTTP
    id: http
    host-env: INGREDIENT_GURU_HOST
entrypoint: service.p6
env:  []
id: ingredient.guru
name: ingredient.guru
...