---
name: ingredient.guru
cro: 1
id: ingredient.guru
env:  []
endpoints: 
  - 
    protocol: http
    id: http
    name: HTTP
    port-env: INGREDIENT_GURU_PORT
    host-env: INGREDIENT_GURU_HOST
links:  []
entrypoint: service.p6
...