---
name: cro-server
entrypoint: service.p6
links:  []
env:  []
id: cro-server
endpoints: 
  - 
    name: HTTP
    host-env: CRO_SERVER_HOST
    protocol: http
    port-env: CRO_SERVER_PORT
    id: http
cro: 1
...
